### ISSUE TITLE
Campaign Piloting Use Case

### ISSUE THREAD

**Issue by nchrys** [csharrison/aggregate-reporting-api#6]
Hello,

Advertisers currently have very tight control over the budget they spend on the various online marketing channels they run simultaneously. Many uses cases demand the ability to start / stop / increase / decrease the spend on a campaign with low latency (seasonal sales, urgency management, campaign ramp-ups, ...). Most of the times the latency requirement is in the order of the day, but in some cases such as seasonal sales advertiser want even lower latency, in the order of the hour.

The aggregated reporting proposition talks about reports with delays up to a day. This would mean reacting at the superior order to magnitude if you want to observe a trend. Advertisers would thus pilot their campaigns weekly at best. This sounds quite out of touch with the current use cases.

Could a much more frequent aggregated reporting (hourly basis) be considered to enable a form of campaign piloting?

**Comment by michaelkleber** [comment]
Hello Nicolas, I have a few questions about your question.

First, are you thinking about ad campaigns served through the [TURTLEDOVE](https://github.com/michaelkleber/turtledove) interest-group mechanism?  That's the thing we've proposed that relies on something like this Aggregated Reporting API to count impressions.  If you're not focused on TURTLEDOVE then please help me understand how you'd be using this API.

Second, are you focused just on single-site data here?  That is, for something like impression counting in TURTLEDOVE, there's no need to create a single report in which one browser collects information from across multiple domains it visits.  In that case, the only goal Aggregate Reporting is serving is to prevent a timing attack aimed at thwarting the protections while [rendering the ad](https://github.com/michaelkleber/turtledove#rendering-the-winning-ad).  A simpler API than the one described here might suffice for that narrow use case, and perhaps could preserve privacy without as much reporting delay.

**Comment by nchrys** [comment]
Hi Michael,

Thank you for your response.

> First, are you thinking about ad campaigns served through the TURTLEDOVE interest-group mechanism?

Yes, indeed I am thinking about ad campaigns that would be served through TurtleDove or a similar privacy-friendly alternative. I assumed these two proposals are meant to be used together.

> Second, are you focused just on single-site data here?

Yes, this use case is about campaign-level reporting for the advertiser, "single-site data" if I understand correctly.

> A simpler API than the one described here might suffice for that narrow use case, and perhaps could preserve privacy without as much reporting delay.

Agreed, it seems that the Aggregate Reporting API cannot cover this use case. 

To cover it, either the delay should be reduced, or another API with a different set of restrictions should be set up.

For Campaign Budget Piloting the requirements would be :

- Aggregation Level: Campaign
- Delay: very short (ideally a random delay of ~1 min)
- Noise sensibility: there can be a little added noise

In our opinion, this is something all actors in the industry could work with without weakening the proposal's commitment to privacy.

**Comment by michaelkleber** [comment]
This topic is being discussed over at https://github.com/WICG/conversion-measurement-api/issues/39.

As @csharrison says over in that other issue, I think we should be able to support these kinds of use cases with something like a up-to-1-hour reporting delay.
